### ISSUE TITLE
Tip: built files are meant to be served over an HTTP server.   Opening index.html over file:// won't work.

### ISSUE THREAD

**Issue by L1114** [cccyb/vue-eleme-app#2]
请问为什么你打包过后的dist目录下的index.html可以点击直接在浏览器打开，并不需要像提示上所说的那样访问？

**Comment by cccyb** [comment]
可能是因为我把mock数据直接引入了，而不是通过express服务器来请求的原因，我这里是取巧了，一般的项目打包后都是需要服务器支持的。
